In [ ]:
#importing
import numpy as np
#Random module is sub-package of numpy

In [ ]:
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A = np.random.rand(1)
print(A)

[0.5221151]


In [ ]:
A = np.random.rand(8,4)    #rand range is between 0 and 1
print(A)

[[0.74094154 0.03897877 0.93843002 0.73457896]
 [0.20678594 0.05334917 0.83396649 0.96352537]
 [0.84325167 0.67539542 0.81064312 0.47162191]
 [0.85603832 0.77779382 0.4623684  0.93978835]
 [0.82693697 0.97384455 0.36729248 0.26172291]
 [0.56891054 0.42628228 0.49573665 0.14453148]
 [0.43721581 0.54153659 0.72403451 0.57722287]
 [0.92328484 0.2019674  0.32200592 0.72242704]]


In [ ]:
A = np.floor(10*np.random.rand(8,4))
print(A)

[[3. 2. 4. 3.]
 [2. 9. 9. 5.]
 [2. 0. 2. 3.]
 [3. 3. 6. 7.]
 [7. 1. 9. 6.]
 [8. 6. 1. 8.]
 [0. 7. 5. 9.]
 [8. 9. 7. 2.]]


In [ ]:
A = np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
print(np.vsplit(A,4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
print(np.vsplit(A,2))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
np.vsplit(A,(2,7))

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,6))#split it after 3rd row and 6th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,5))    #split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
A = np.arange(1,33).reshape(4,8)
print(A)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(A,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(A,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
A = [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B = np.rad2deg(A)
print(B)    #convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:
A = [45,60,90,180]    #convert degrees to radians
np.deg2rad(A)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
st = np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C = np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
#linalg is another sub-package in numpy - Linear Algebra
print(np.linalg.inv(C))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
C = np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(C))

23


In [ ]:
D=np.floor(10*np.random.rand(24).reshape(6,4))
print(D)
print(np.argmax(D))

[[5. 5. 3. 9.]
 [2. 3. 4. 0.]
 [7. 3. 6. 9.]
 [1. 4. 2. 4.]
 [8. 4. 2. 3.]
 [0. 9. 7. 6.]]
3


In [ ]:
D=10*np.random.rand(24).reshape(6,4)
print(D)

[[1.73317185 3.40584313 7.992244   9.48933393]
 [2.24548179 5.66830914 6.76509491 1.90049693]
 [9.40414991 9.28671636 5.15914322 7.1731764 ]
 [8.62817777 8.5316746  9.23472824 3.98964857]
 [4.27411473 1.53898063 4.02846148 8.92598097]
 [9.35703165 7.28818054 2.13925961 7.3519779 ]]


In [ ]:
np.argmax(D)

3

In [ ]:
np.argmax(D,axis=0)   #columns

array([2, 2, 3, 0])

In [ ]:
np.argmax(D,axis=1)   #rows

array([3, 2, 0, 2, 3, 0])

In [ ]:
np.argmin(D)

17

In [ ]:
np.argmin(D,axis=0)

array([0, 4, 5, 1])

In [ ]:
np.argmin(D,axis=1)

array([0, 3, 2, 3, 1, 2])

Searching

In [ ]:
#find the indexes where the values are even
a=np.array([34,56,7,17,88,91])
print(np.where(a%2 == 0))

(array([0, 1, 4]),)


In [ ]:
#used only for already sorted list
a = np.array([6,7,8,9,10])
x = np.searchsorted(a,10)
print(x)

4


In [ ]:
#find the indexes where the values are divisible by 6
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
#used only for already sorted list
a = np.array([6,7,8,9,10])
x = np.searchsorted(a,22)
print(x)

#gives wrong output for unsorted list

5


In [ ]:
#sorting array
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([True, False , True])    #False=0  and True=0
print(np.sort(arr))

[False  True  True]


In [ ]:
#2nd sort - sorting happens within row
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#array filter
arr = np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]   #filter list
newarr = arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
arr = np.array([40,42,50,44,67,78])
filt = np.where(arr%2==0)
print(filt)
print(arr[filt])                      #filter can be list or an array

(array([0, 1, 2, 3, 5]),)
[40 42 50 44 78]


In [ ]:
#zip function is used to combine two or more arrays and lists
names = np.array(["Akhila","Sasi","Prasanna","Lavanya"])
initials = np.array(["T","P","N","P"])
for i,j in zip(initials,names):
  print(i,".",j)

T . Akhila
P . Sasi
N . Prasanna
P . Lavanya


In [ ]:
names = np.array(["Akhila","Sasi","Prasanna","Lavanya"])
initials = np.array(["T","P","N","P"])
rollno = np.array(["5C0","5B0","5A6","5B1"])
for i,j,k in zip(initials,names,rollno):
  print(i,".",j,"-",k)

T . Akhila - 5C0
P . Sasi - 5B0
N . Prasanna - 5A6
P . Lavanya - 5B1


In [ ]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
a = np.multiply(a1,a2)
print(a)

[ 200  420  660  920 1200 1500]


In [ ]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
b=np.divide(a1,a2)
print(b)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
c=np.mod(a1,a2)
print(c)

[10 20  8 17  2 10]


In [ ]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
d=np.divmod(a1,a2)
print(d)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


Logarithms

In [ ]:
a = 1.2
print(np.log(a))   #natural log e

0.1823215567939546


In [ ]:
a = 1.2
print(np.log2(a))    #log base 2

0.2630344058337938


In [ ]:
a = 1.2
print(np.log10(a))   #log base 10

0.07918124604762482


In [ ]:
a = np.array([1,2,3,4,5])
print(np.log(a))   #natural log

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
a1 = np.arange(1,10)
print(a1)
print(np.log10(a1))    #base 10

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Other mathematical Operations

In [ ]:
a2 = np.array([5,6,7,10])
x = np.cumsum(a2)
print(x)

[ 5 11 18 28]


In [ ]:
a2 = np.array([5,6,7,10])
x = np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a1 = np.array([10,15,25,15])   #e2-e1
newarr = np.diff(a1)
print(newarr)

[  5  10 -10]


In [ ]:
#lcm
num1 = 455
num2 = 665
x = np.lcm(num1,num2)
print(x)

8645


In [ ]:
#gcd
num1 = 455
num2 = 665
x = np.gcd(num1,num2)
print(x)

35


In [ ]:
a = np.array([12,15,60])
gc = np.gcd.reduce(a)       #takes multiple inputs gives single output
print(gc)

3


In [ ]:
a = np.array([12,15,60])
lc = np.lcm.reduce(a)       #takes multiple inputs gives single output
print(lc)

60


In [ ]:
a = np.array([5,10,15,20])
s = np.cumsum.reduce(a)
print(s)

AttributeError: 'function' object has no attribute 'reduce'